trigger: none

pr:
  branches:
    include:
    - main
  paths:
    exclude: # file paths which will not trigger a build
    - README.md
    - .gitignore

pool: Default

steps: 
- script: |
    if ! command -v cppcheck &> /dev/null
    then
      echo "cppcheck not found, installing..."
      sudo apt-get update
      sudo apt-get install -y cppcheck
    else
      echo "cppcheck already installed"
    fi
  displayName: 'Install cppcheck'

- script: |
    cppcheck --version
    cppcheck --enable=all ./src/track1/*.*
    cppcheck --enable=all ./src/track2/*.*
  displayName: 'Run cppcheck'

- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'

- task: Application security testing@2023
  inputs:
    projectName: 'checkmarx'
    enableProxy: true
    enableSastScan: true
    fullScansScheduled: true
    denyProject: true
    generatePDFReport: true
    vulnerabilityThreshold: true
    failBuildForNewVulnerabilitiesEnabled: true
    enablePolicyViolations: true
    avoidDuplicateScans: true
    enableDependencyScan: false

